// ── Meta-Loop Types ───────────────────────────────────────────────────────
// Shared types for the self-evolving meta-loop.
// Imported by all meta-loop modules via `../types/meta-types.js`.

import type { AgentRole } from "./agent-types.js";

/** One run's aggregated signals, written to runs.jsonl. */
export interface RunSummary {
  runId: string;
  timestamp: string;
  ideaHash: string;
  status: "complete" | "partial" | "failed";
  totalAgents: number;
  totalTokens: { input: number; output: number };
  totalDurationMs: number;
  actionableCritiques: number;
  critiqueBreakdown: { critical: number; high: number; medium: number; low: number; none: number };
  governanceDenials: number;
  appliedProposalIds: string[];
  promptVersion: string;
  governanceVersion: string;
  roleMetrics: Record<AgentRole, RoleMetric>;
}

/** Per-role metrics for a single run. */
export interface RoleMetric {
  status: "pending" | "in_progress" | "completed" | "failed" | "partial";
  tokenUsage: { input: number; output: number };
  durationMs: number;
  reputationScore?: number;
}

/** Sliding window aggregate — input to proposer rules. */
export interface SignalWindow {
  windowSize: number;
  roleWindows: Record<AgentRole, RoleWindow>;
  pairWindows: Record<string, PairWindow>;
  governanceDenials: Record<string, number>;
  fixAcceptanceRate: number;
  totalRuns: number;
}

/** Per-role window aggregate. */
export interface RoleWindow {
  role: AgentRole;
  runCount: number;
  failureRate: number;
  avgTokenUtilization: number;
  avgDurationMs: number;
  avgSeverity: number;
  reputationTrend: number;
  emptyOutputCount: number;
}

/** Per-review-pair window aggregate. */
export interface PairWindow {
  reviewer: AgentRole;
  reviewee: AgentRole;
  totalCritiques: number;
  avgFindingsCount: number;
  severityDistribution: { critical: number; high: number; medium: number; low: number; none: number };
  fixAcceptanceRate: number;
}

/** A proposed change generated by a proposer rule. */
export interface ProposedChange {
  proposalId: string;
  createdAt: string;
  sourceFile: string;
  patch: string; // JSON-encoded (varies by category)
  beforeHash: string;
  afterHash: string;
  category: ProposalCategory;
  ruleId: string;
  confidence: number;
  signals: string[];
  status: ProposalStatus;
  provenance: { runId: string; ruleId: string };
  appliedAt?: string;
  rejectionReason?: string;
  rolledBackAt?: string;
}

/** Categories of proposals the meta-loop can generate. */
export type ProposalCategory = "prompt" | "review-pair" | "token" | "governance" | "ceo-config" | "empty-output" | "severity-trend";

/** Proposal lifecycle status. */
export type ProposalStatus = "pending" | "applied" | "rejected" | "rolled-back";

/** Meta-loop configuration. */
export interface MetaLoopConfig {
  enabled: boolean;
  mode: "advisory" | "capture" | "propose" | "apply" | "auto";
  windowSize: number;
  minConfidence: number;
  maxPromptEditsPerRun: number;
  maxGovernanceTuningsPerRun: number;
  maxCEOLeverChangesPerRun: number;
  debounceMs: number;
  allowedLevers: string[];
  allowedLeverDelta: number;
}

/** Default meta-loop configuration. */
export const DEFAULT_META_LOOP_CONFIG: MetaLoopConfig = {
  enabled: false,
  mode: "advisory",
  windowSize: 5,
  minConfidence: 0.7,
  maxPromptEditsPerRun: 2,
  maxGovernanceTuningsPerRun: 1,
  maxCEOLeverChangesPerRun: 1,
  debounceMs: 300000,
  allowedLevers: ["maxIterations", "minSeverity", "maxConcurrent", "escalationThreshold", "reputationDelta", "memoryImportance"],
  allowedLeverDelta: 1,
};